filebeat.inputs:
  - type: docker
    containers.ids:
      - '*'
    processors:
      - add_docker_metadata: ~

  - type: log
    enabled: true
    paths:
      - ./nginx/logs/*.log  # Adjust the path as needed
    fields:
      log_type: nginx
output.logstash:
  hosts: ["logstash_host:5044"]
